add clean install package and check already install

diff --git a/awscli-setup b/awscli-setup
--- a/awscli-setup
+++ b/awscli-setup
@@ -13,44 +13,55 @@ awscli="awscli-bundle"
 tmpdir="/tmp"
 
 stop() {
-	exit 0
+  exit 0
 }
 
 check_env(){
-	if [[ `which python` ]]; then
-		py_ver=`python --version 2>&1`
-		echo "The AWS CLI will be install in $py_ver"
-	else
-		echo "**check**: python not install."
-		exit 0
-	fi
+  if [[ `which python` ]]; then
+    py_ver=`python --version 2>&1`
+    echo "The AWS CLI will be install in $py_ver"
+  else
+    echo "**check**: python not install."
+    exit 0
+  fi
 }
 
 get_package() {
-	echo -n "Download awscli package ..."
-	wget -q "$awsuri" -P "$tmpdir"
-	if [[ 0 -eq $? ]]; then
-		echo "OK"
-	else
-		echo "fail"
-		exit 0
-	fi
+  echo -n "Download awscli package ..."
+  wget -q "$awsuri" -P "$tmpdir"
+  if [[ 0 -eq $? ]]; then
+    echo "OK"
+  else
+    echo "fail"
+    exit 0
+  fi
 }
 
 awscli_install() {
-	check_env
-	get_package
-	echo -n "unzip $awscli.zip ..."
-	unzip -q ${tmpdir}/${awscli}.zip -d /tmp
-	if [[ 0 -eq $? ]]; then
-		echo "OK"
-	else
-		echo "fail"
-		exit 0
-	fi
+  check_env
+  get_package
+  echo -n "unzip $awscli.zip ..."
+  unzip -q ${tmpdir}/${awscli}.zip -d /tmp
+  if [[ 0 -eq $? ]]; then
+    echo "OK"
+  else
+    echo "fail"
+    exit 0
+  fi
 
-	echo "Install awscli ..."
-	${tmpdir}/${awscli}/install -i "$prefix" -b "$prefix_bin"
+  echo "Install awscli ..."
+  ${tmpdir}/${awscli}/install -i "$prefix" -b "$prefix_bin"
+  if [ $? -eq 0 ]; then
+    rm -rf ${tmpdir}/${awscli}
+    echo "clean install package file finish."
+  else
+    echo "Install awscli failed"
+  fi
 }
 
-awscli_install
+if which aws; then
+  echo "$(which aws) already exist."
+else
+  awscli_install
+fi
+
